### ISSUE TITLE
Work from 10.9.0 and NOT work from 10.9.1

### ISSUE THREAD

**Issue by Ales999** [toleda/audio_ALC898#1]
Please update/upgrade for 10.9.1 version.

PS Sorry for my bad english.
PSPS MB: GA-Z77X-UP5 TH

**Comment by MysticalOS** [comment]
It still works on 10.9.1, even works on 10.9.2 betas. It's just an older version, so probably lacks whatever apple changed/fixed in 2.5.3 and 2.5.4

**Comment by Ales999** [comment]
Bug for me:

Macintosh:audio_ALC898-master admin$ ./audio_alc898-91_patch.command 
Prepare Desktop/audio_ALC898 ...
Archive:  898.zip
   creating: 898/
  inflating: 898/Info-84.plist  
  inflating: 898/Info-85.plist  
  inflating: 898/Info-90.plist  
  inflating: 898/Info-91.plist  
 extracting: 898/layout1.xml.zlib  
 extracting: 898/layout2.xml.zlib  
 extracting: 898/layout3.xml.zlib  
  inflating: 898/Platforms.xml.zlib  
Install files ...
Password:
rm: /System/Library/Extensions/AppleHDA.kext/Contents/Resources/*.zlib: No such file or directory
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
Patch binary ...
Fix permissions ...
Kernel cache...
Finished, restart required.
Macintosh:audio_ALC898-master admin$

**Comment by toleda** [comment]
The script says AppleHDA.kext is not installed in S/L/E.  

From README:
Requirements
1. Native S/L/E/AppleHDA.kext (restore native AppleHDA.kext with Combo Update)

**Comment by Ales999** [comment]
Ah, my backup AppleHDA.kext is bad, restored from combo and patch is working, thanks.
Closed issue.
