### ISSUE TITLE
script error Info-92.plist

### ISSUE THREAD

**Issue by cwestpha** [toleda/audio_ALC898#2]
Consistently running the 898 10.9.2 script for patching GM 10.9.2 AppleHDA results in an error when it comes to installing of info-92.plist. This error is repeatable and reproducible all of the time on my machine. 

Terminal Output: 
Prepare Desktop/audio_ALC898 ...
Install files ...
Password:
Sorry, try again.
Password:
install: Info-92.plist: No such file or directory
Patch binary ...
Fix permissions ...
Kernel cache...
Finished, restart required.

Console Output:
sudo[4356]: cwestpha : TTY=ttys000 ; PWD=/Users/cwestpha/Desktop/audio_ALC898/898 ; USER=root ; COMMAND=/bin/rm -R /System/Library/Extensions/AppleHDA.kext/Contents/Plugins/AppleHDAHardwareConfigDriver.kext/Contents/Info.plist
sudo[4362]: cwestpha : TTY=ttys000 ; PWD=/Users/cwestpha/Desktop/audio_ALC898/898 ; USER=root ; COMMAND=/usr/bin/install -m 644 -o root -g wheel Info-92.plist /System/Library/Extensions/AppleHDA.kext/Contents/Plugins/AppleHDAHardwareConfigDriver.kext/Contents/Info.plist
sudo[4364]: cwestpha : TTY=ttys000 ; PWD=/Users/cwestpha/Desktop/audio_ALC898/898 ; USER=root ; COMMAND=/bin/rm -R /System/Library/Extensions/AppleHDA.kext/Contents/Resources/layout120.xml.zlib /System/Library/Extensions/AppleHDA.kext/Contents/Resources/layout90.xml.zlib /System/Library/Extensions/AppleHDA.kext/Contents/Resources/layout92.xml.zlib /System/Library/Extensions/AppleHDA.kext/Contents/Resources/layout93.xml.zlib /System/Library/Extensions/AppleHDA.kext/Contents/Resources/layout94.xml.zlib
sudo[4366]: cwestpha : TTY=ttys000 ; PWD=/Users/cwestpha/Desktop/audio_ALC898/898 ; USER=root ; COMMAND=/usr/bin/install -m 644 -o root -g wheel Platforms.xml.zlib layout1.xml.zlib layout2.xml.zlib layout3.xml.zlib /System/Library/Extensions/AppleHDA.kext/Contents/Resources
sudo[4368]: cwestpha : TTY=ttys000 ; PWD=/Users/cwestpha/Desktop/audio_ALC898/898 ; USER=root ; COMMAND=/usr/bin/perl -pi -e s|\x8b\x19\xd4\x11|\x99\x08\xec\x10|g /System/Library/Extensions/AppleHDA.kext/Contents/MacOS/AppleHDA
sudo[4370]: cwestpha : TTY=ttys000 ; PWD=/Users/cwestpha/Desktop/audio_ALC898/898 ; USER=root ; COMMAND=/usr/sbin/chown -R root:wheel /System/Library/Extensions/AppleHDA.kext
sudo[4372]: cwestpha : TTY=ttys000 ; PWD=/Users/cwestpha/Desktop/audio_ALC898/898 ; USER=root ; COMMAND=/usr/bin/touch /System/Library/Extensions

I think OS X isn't liking the combined rename with new permissions and ownership in a single line. I can fix this issue by separating it into two steps, and everything works fine. Without it, the modified info.plist is never moved back into .kext and thus results in onboard audio failing to function on reboot.

**Comment by toleda** [comment]
Do not see the error.  Nothing wrong with the command; worked with the other files.  Suspect you downloaded the new audio_ALC898-master onto an existing Downloads/audio_ALC898-master.  Result is the new folder (-92) is inside the old folder (-91). The script will not see the Info-92.plist file.

My log:
Last login: Sun Mar 23 21:54:44 on console
...$ /Users/.../Downloads/audio_ALC898-master/audio_alc898-92_patch.command ; exit;

Prepare Desktop/audio_ALC898 ...
Install files ...
Password:
Patch binary ...
Fix permissions ...
Kernel cache...
Finished, restart required.
logout

[Process completed]

**Comment by cwestpha** [comment]
Yep I found the issue. Your assuming everyone will just grab the .zip and use the built-in unarchiver with no one using github sync to grab it. Since you hard coded in audio_ALC898-master (something that would never exist if you're using a github client or command since -master is appended to the file name when grabbing a full folder or project). Your code breaks the script for anyone not using the web interface & is using the pro or shell tools.

**Comment by drewhammond** [comment]
+1 on the issue mentioned above. It's really bad practice to hardcode the paths to downloaded files. Use $(dirname $0) or [another method](http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in) to get the current directory of your script and make all subsequent paths relative from there.

**Comment by toleda** [comment]
Apologies, haven't gotten to that level.  If not resolving this issue is unacceptable, I'll take the repos down.
