### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by nayanseth** [toleda/audio_ALC898#4]
I tried installing the codec using multibeast on 10.10, it worked at first but on reboot it stopped working. Next I tried updating the AppleHDA.kext to the original file and then used the .command file to install the codec but it didnt work. What should I do next? No Sound!!

**Comment by toleda** [comment]
Yosemite release, see README.

**Comment by nayanseth** [comment]
I followed the procedure given in the readme of https://github.com/toleda/audio_RealtekALC and it did replace the native AppleHDA.kext but the sound button in status bar remained disabled. Am I missing something?

**Comment by toleda** [comment]
What are the choices in System Preferences/Sound/Output?

**Comment by nayanseth** [comment]
@toleda After performing the procedure the speaker does make some crackling sound, but once i login, sound is disabled.

![screen shot 2014-10-22 at 9 15 07 am](https://cloud.githubusercontent.com/assets/3462785/4730700/e3206974-599d-11e4-8a92-2b7c19e6fb37.png)

**Comment by toleda** [comment]
What color port are your speakers connected?

**Comment by nayanseth** [comment]
@toleda I have connected it to the CPU Panels Audio Out.

**Comment by nayanseth** [comment]
@toleda It seems the wire wasnt connected properly. I had to tilt the cable and the Internal Speakers got changed to Headphones Port. Thanks a lot for all the help!

![screen shot 2014-10-22 at 2 56 06 pm](https://cloud.githubusercontent.com/assets/3462785/4733892/8e591f3c-59cd-11e4-97e3-19c08dede88c.png)
